services:
  acbc:
    build: .
    image: acbc:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ~/data/acbc-storage/acbc:/data
      - ./configs/production.yaml:/app/configs/production.yaml:ro
